{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-network-policy
  labels:
    {{- include "multi-container-app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "multi-container-app.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from the same app
    - from:
        - podSelector:
            matchLabels:
              {{- include "multi-container-app.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 5432
    # Allow traffic from the ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8080
  egress:
    # Allow all outbound traffic
    - {}
{{- end }}