version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${REGISTRY_URL:-localhost:5000}/k3s-app/frontend:${TAG:-latest}
    ports:
      - "8080:80"
    environment:
      - API_URL=http://backend:8080/api
    volumes:
      - shared-data:/usr/share/nginx/html/data
    depends_on:
      - backend

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${REGISTRY_URL:-localhost:5000}/k3s-app/backend:${TAG:-latest}
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/app_database
      - LOG_LEVEL=info
    volumes:
      - shared-data:/data
    depends_on:
      - database

  # Database service
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: ${REGISTRY_URL:-localhost:5000}/k3s-app/database:${TAG:-latest}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_database
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  shared-data:
  postgres-data: